server:
  port: 8084
topic:
  name: sending.something
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springfox:
  documentation:
    swaggerUi:
      baseUrl: /api/doc

spring:
  kafka:
    consumer:
      group-id: "default"
  profiles:
    active: native
  application:
    name: market-email
